name: 'tag-differ'
description: 'Diff firebase tags'
author: 'Invertase'
inputs:
  extenstions:
    required: true
    description: 'comma seperated list of file extensions to include'
    default: 'js,kt,java,swift'
  github-token:
    required: true
    description: 'github token'
runs:
  using: 'node16'
  main: 'dist/index.js'
