name: 'tag-differ'
description: 'Diff firebase tags'
author: 'Invertase'
inputs:
  base-ref:
    required: false
    description: 'base ref to compare against'
  extensions:
    required: true
    description: 'comma seperated list of file extensions to include'
    default: 'js,ts,kt,java,swift'
  github-token:
    required: true
    description: 'github token'
  included-types:
    description: |
      comma seperated list of types of diffs. 
      Accepted values are 'added', 'removed' and 'changed'
    default: 'added,removed,changed'
  inluded-change-types:
    description: |
      comma seperated list of types of changes for the 'changed' subtype. 
      Accepted values are 'file_path',line_number' and 'code_contents'
    default: 'file_path,line_number,code_contents'
runs:
  using: 'node16'
  main: 'dist/index.js'
